### ISSUE TITLE
Windows 10 Crash

### ISSUE THREAD

**Issue by nickrod518** [1RedOne/Invoke-Clippy#1]
Clippy, pls help! Upon running within the PS ISE in Windows 10, the ISE process immediately closes.

**Comment by 1RedOne** [comment]
This is an intended feature.  

No seriously, we're intentionally hiding the spawning powershell process.  If you'd like to keep the powershell window open, comment out the lines `149-151` and replace those with `$window.Show()`.

**Comment by nickrod518** [comment]
Ah ok, that makes sense!

**Comment by 1RedOne** [comment]
In the next release, I'll make '-DisplayDelay' or something similar as a param, so he appears immediately. Would it be good to have the option of spawning him without hiding the window?

**Comment by nickrod518** [comment]
I think it would be because my case was that I had a bunch of scripts open in the ISE and it just disappeared. Is the Clippy function smart enough to hide only his own PowerShell instance, or does it hide all instances of PowerShell processes? In my mind, that could be a big deal.
On Apr 2, 2016 8:30 AM, Stephen Owen notifications@github.com wrote:In the next release, I'll make '-DisplayDelay' or something similar as a param, so he appears immediately. Would it be good to have the option of spawning him without hiding the window?

**Comment by 1RedOne** [comment]
It hides the instance from which it was launched.

**Comment by nickrod518** [comment]
I think if it's as simple as adding a switch param and wrapping those lines around 150 in an 'if', then why not. I will do it and submit my very first Pull request if you accept those. What do you think? 
On Apr 2, 2016 9:14 AM, Stephen Owen notifications@github.com wrote:It hides the instance from which it was launched.

**Comment by 1RedOne** [comment]
Yeah, sounds good!  

to do this you coud take the current display steps under `#hide PowerShell` and put that script block in a switch block.  You could then add an `else{   }` scriptblock after it and add `$Window.Show()
$Window.Activate()` to display instead.  I think!
