### ISSUE TITLE
Button Visibility is Hidden in the version on Github

### ISSUE THREAD

**Issue by gerane** [1RedOne/Invoke-Clippy#6]
I wasn't sure if the version her on Github is different that the one on the gallery. 

I just made a Pull Request to fix the image path, but then when I was looking into the buttons missing for me I noticed they were set to hidden. The format ps1xml was empty as well. I figured I would ask if they were different or if you were still working on this before I dug any further.

Another idea I had was finding the original clippy tray icon and using that. I also might look into adding invoking it without the tray.

**Comment by 1RedOne** [comment]
The format ps1xml is an artifact ( I copied another module and changed the names!  )  

We don't actually have any custom types here, for the format.ps1xml file isn't needed, I'll remove it.

Adding the Clippy icon sounds hilarious!  do it!
